### ISSUE TITLE
panicked at parser.rs: byte index 6 is out of bounds

### ISSUE THREAD

**Issue by doncato** [tsirysndr/upnp-client-rs#12]
Hello there,

I am trying to use this library to control a [gmrender](https://github.com/hzeller/gmrender-resurrect) instance. So far I was able to set a URL to play. But while trying to get the position it seems that the parser for the position crashes with the following message:

```
thread 'actix-rt|system:0|arbiter:0' panicked at /home/doncato/.cargo/registry/src/index.crates.io-6f17d22bba15001f/upnp-client-0.1.9/src/parser.rs:312:27: byte index 6 is out of bounds of `00035`
```

The number at the end correctly corresponds to the number of the position in the track (in the case above 35s)

Is this perhaps a bug in the parser or is gmrender maybe responding unexpectedly? In either case how can this be fixed?

**Comment by tsirysndr** [comment]
Hi @doncato , 

thanks for reporting the issue, 
I think `00035` is incorrect , `RelTime`  value from [gmrender](https://github.com/hzeller/gmrender-resurrect) must correspond to `00:00:35` and converted into `000035`

**Comment by tsirysndr** [comment]
or we need to rewrite the parser here https://github.com/tsirysndr/upnp-client-rs/blob/215044da0a9e8ef6107f97e1dd295af485914808/src/parser.rs#L310

split the `position_str` at `:`  https://github.com/tsirysndr/upnp-client-rs/blob/215044da0a9e8ef6107f97e1dd295af485914808/src/parser.rs#L301 and parse hours, minutes, seconds

**Comment by doncato** [comment]
Thanks for the fast response :+1: 

I took a look in the [UPnP AVTransport v3 Service](http://www.upnp.org/specs/av/UPnP-av-AVTransport-v3-Service-20101231.pdf) that you linked in the Projects README, which states in Section 2.2.23 on page 36:
> The time format used for the RelativeTimePosition state variable is the same as for state variable
CurrentTrackDuration.

And states on Page 34/34 in Section 2.2.15 that the CurrentTrackDuration is:
> [...] specified as a string of the
following form:
H+:MM:SS[.F+] or H+:MM:SS[.F0/F1]
> where:
> - H+ means one or more digits to indicate elapsed hours
> - MM means exactly 2 digits to indicate minutes (00 to 59)
> - SS means exactly 2 digits to indicate seconds (00 to 59)
> - [.F+] means OPTIONALLY a dot followed by one or more digits to indicate fractions of seconds
> - [.F0/F1] means OPTIONALLY a dot followed by a fraction, with F0 and F1 at least one digit long,
and F0 < F1

As long as I didn't misinterpret something, it seems that the standard does allow for the server to respond with something like `0:00:35` which then results in `00035` (5 digits). Under this aspect I think adapting the parser would be adequate.

As for how I would suggest to use something like [split](https://doc.rust-lang.org/std/primitive.str.html#method.split) instead of `replace` in https://github.com/tsirysndr/upnp-client-rs/blob/215044da0a9e8ef6107f97e1dd295af485914808/src/parser.rs#L301

And then using for example `next()` on the resulting iterator to get `hours`, `minutes` and `seconds` in https://github.com/tsirysndr/upnp-client-rs/blob/215044da0a9e8ef6107f97e1dd295af485914808/src/parser.rs#L310

**Comment by doncato** [comment]
I made some changes to the parser (see #13), with those changes I can successfully get the Position from the gmrender instance. I tested to obtain around 10-20 values from the gmrender instance ranging between 0s and 1h05m30s seemed to work so far, unfortunately I cannot really test whether it still works with 2 digits for the hours but I would assume (or hope) that it does
